//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartShift.Core.Service.Resourcess {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ExceptionResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartShift.Core.Service.Resourcess.ExceptionResources", typeof(ExceptionResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Email is Incorrect Or Not Register.
        /// </summary>
        internal static string sAuthService_Login_EmailNotExist {
            get {
                return ResourceManager.GetString("sAuthService_Login_EmailNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Your Password is Incorrect.
        /// </summary>
        internal static string sAuthService_Login_PasswordIsIncorrect {
            get {
                return ResourceManager.GetString("sAuthService_Login_PasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Email already exists..
        /// </summary>
        internal static string sAuthService_Register_EmailAlreadyExists {
            get {
                return ResourceManager.GetString("sAuthService_Register_EmailAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Invalid user role..
        /// </summary>
        internal static string sAuthService_Register_InvalidUserRole {
            get {
                return ResourceManager.GetString("sAuthService_Register_InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, Field Company Name Cannot Be Empty.
        /// </summary>
        internal static string sCompanyService_CreateCompany_MissingCompanyName {
            get {
                return ResourceManager.GetString("sCompanyService_CreateCompany_MissingCompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, End Date Time Must Bigger than Start Date Time .
        /// </summary>
        internal static string sShift_CreateShift_EndDateLowerThanStart {
            get {
                return ResourceManager.GetString("sShift_CreateShift_EndDateLowerThanStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User, User Id Don&apos;t be Found.
        /// </summary>
        internal static string sShift_CreateShift_InvalidUserRole {
            get {
                return ResourceManager.GetString("sShift_CreateShift_InvalidUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User ,You are not a member of that company.
        /// </summary>
        internal static string sShift_CreateShift_NotMemberCompany {
            get {
                return ResourceManager.GetString("sShift_CreateShift_NotMemberCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User ,Shift overlaps an existing shift.
        /// </summary>
        internal static string sShift_CreateShift_ShiftOverLap {
            get {
                return ResourceManager.GetString("sShift_CreateShift_ShiftOverLap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User ,You Don&apos;t Have Permission To Edit Shift.
        /// </summary>
        internal static string sShift_UpdateShift_NoAccess {
            get {
                return ResourceManager.GetString("sShift_UpdateShift_NoAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dear User ,Shift not found.
        /// </summary>
        internal static string sShift_UpdateShift_ShiftNotFound {
            get {
                return ResourceManager.GetString("sShift_UpdateShift_ShiftNotFound", resourceCulture);
            }
        }
    }
}
