// <auto-generated />
namespace SmartShift.Core.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class Day3Company : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Day3Company));
        
        string IMigrationMetadata.Id
        {
            get { return "202510231555574_Day3Company"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
